apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-poc
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: ch-central
      port: 9000
      protocol: native
      secure: false
      username: default
      defaultDatabase: otel
      dialTimeout: 10
      queryTimeout: 60
    secureJsonData:
      password: "clickhouse"
